name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
- master

pr:
  branches:
    include:
    - '*'


resources:
  containers:
  - container: python37
    image: python:3.7-slim-buster

jobs:
- job: py37
  pool:
    vmImage: 'Ubuntu-16.04'
  container: python37
  steps:
  - script: pip install --user tox
  - script: ~/.local/bin/tox -e py37
- job: pep8
  pool:
    vmImage: 'Ubuntu-16.04'
  container: python37
  steps:
  - script: pip install --user tox
  - script: ~/.local/bin/tox -e flake8
- job: pylint
  pool:
    vmImage: 'Ubuntu-16.04'
  container: python37
  steps:
  - script: pip install --user tox
  - script: ~/.local/bin/tox -e pylint
