name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
- master

pr:
  branches:
    include:
    - '*'


resources:
  containers:
  - container: python37
    image: python:3.7-slim-buster

jobs:
- job: Setup
  pool:
    vmImage: 'Ubuntu-16.04'
  container: python37
  steps:
  - script: pip install tox
- job: py37
  pool:
    vmImage: 'Ubuntu-16.04'
  container: python37
  dependsOn: Setup
  steps:
  - script: tox -e py37'
- job: pep8
  pool:
    vmImage: 'Ubuntu-16.04'
  container: python37
  dependsOn: Setup
  steps:
  - script: tox -e flake8
- job: pylint
  pool:
    vmImage: 'Ubuntu-16.04'
  container: python37
  dependsOn: Setup
  steps:
  - script: tox -e pylint
