name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
- master

pr:
  branches:
    include:
    - '*'

jobs:
- template: azure-pipelines/python-job.template.yml
  parameters:
    toxenv: 'py37'
    with_publish: true
    publish_options:
      testResultsFormat: 'Junit'
      testResultsFiles: '**/TESTS-*.xml'
- template: azure-pipelines/python-job.template.yml
  parameters:
    toxenv: 'pep8'
- template: azure-pipelines/python-job.template.yml
  parameters:
    toxenv: 'pylint'
