trigger:
- master

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'Ubuntu-16.04'

resources:
  containers:
  - container: python37
    image: python:3.7-slim-buster

jobs:
- job: Setup
  container: python37
  steps:
  - script: pip install tox
- job: py37
  container: python37
  dependsOn: Setup
  steps:
  - script: tox -e py37'
- job: pep8
  container: python37
  dependsOn: Setup
  steps:
  - script: tox -e flake8
- job: pylint
  container: python37
  dependsOn: Setup
  steps:
  - script: tox -e pylint
